# Numpy Arrays

In [2]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [36]:
my_mat = np.array(my_mat)

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.75414562, 0.67986488, 0.38781365, 0.52090663, 0.82357296])

In [24]:
np.random.rand(3,3)

array([[0.8446544 , 0.3683476 , 0.37629752],
       [0.41683605, 0.75838549, 0.09977635],
       [0.89727197, 0.46526685, 0.108367  ]])

In [26]:
np.random.randn(4,4) # standard normal distribution

array([[ 0.78893442, -2.55513332,  0.2636233 ,  0.80288357],
       [-0.61706929,  0.73991246,  2.3378991 , -0.04943087],
       [-1.93423076, -0.95981348,  0.7462402 , -0.84668146],
       [ 0.26809389,  0.60817109,  1.04953297,  0.14725799]])

In [27]:
np.random.randint(1,100)

31

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([19, 35, 35,  3, 33, 29, 46, 19, 16, 18])

In [39]:
my_mat.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
ranarr.max()

46

In [42]:
ranarr.min()

3

In [43]:
ranarr.argmax()

6

In [44]:
ranarr.argmin()

3

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

3

## Indexing and Selection

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

8

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [53]:
arr[5]

5

In [54]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[0:5] = 100

In [57]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [58]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]

In [59]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slice_of_arr[:] = 99

In [61]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [62]:
arr_copy = arr.copy()

In [63]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_copy[:] = 100

In [65]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[0][0]

5

In [73]:
arr_2d[1,0]

20

In [75]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr = arr > 5

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr_2d = np.arange(50).reshape(5,10)

In [84]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [85]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [87]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Operations

In [88]:
arr = np.arange(0,11)

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [93]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [94]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [95]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [96]:
arr / arr 

C:\Users\thoma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [97]:
1 / arr 

C:\Users\thoma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [98]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [100]:
np.sqrt(arr**2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [101]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [102]:
np.max(arr)

10

In [103]:
arr.max()

10

In [104]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [105]:
np.log(arr)

C:\Users\thoma\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

## Create array of 10 zeroes

In [109]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [117]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
np.random.rand(1)

array([0.54681641])

In [138]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [8]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [8]:
mat = np.arange(1,26).reshape(5,5)

In [9]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Write Code Here that Reproduces the Output Of The Cell below Be Careful Not To Run the Cell below, otherwise you wont be able  to see the output any more

In [17]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Write Code here that reproduces the output of the cell below not to run the

In [19]:
mat[3][4]

20

## Write Code here that reproduces the output of the cell below not to run the

In [35]:
mat1 = mat[0:3,1]

In [36]:
mat1

array([ 2,  7, 12])

In [42]:
result = [mat1[0]] + [mat1[1]]

In [44]:
result = [[mat1[0]],[mat1[1]],[mat1[2]]]

In [46]:
np.array(result)

array([[ 2],
       [ 7],
       [12]])

In [47]:
mat[4]

array([21, 22, 23, 24, 25])

In [49]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
np.sum(mat)

325

In [52]:
np.std(mat)

7.211102550927978

In [10]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])